### ISSUE TITLE
hammer++ (CS:GO) isnt set up properly for portal 2

### ISSUE THREAD

**Issue by ArielChandia2** [jean-knapp/xblah-modding-tool-public#1]
while testing the hammer++ with decompiled maps, i noticed how the lights got broken from the original one (with missing materials), then when tested with vanila hammer from the sdk the map properly packed.

https://file.garden/YbJeMftBp0P7hfIi/portal_decomp_plusplus.PNG
(compiled with hammer++)
https://file.garden/YbJeMftBp0P7hfIi/portal_decomp_vanila.PNG
(compiled with vanila hammer)

i dont know if it its from the lights.rad files from what i read, or any file that hasnt been modified to work on portal 2.

**Comment by jean-knapp** [comment]
Interesting. I'll investigate this.

**Comment by jean-knapp** [comment]
We will have to wait for H++ for Portal 2.
