### ISSUE TITLE
Problem in Soundscape Editor

### ISSUE THREAD

**Issue by MaxikMapper** [jean-knapp/xblah-modding-tool-public#10]
Of course, I understand this is a free version, but I would like there to be no such shortcomings. The problem is that when trying to load a scape file that contains floating-point numbers, and if there is a dot between the integer and the fractional number, and not a comma, the following exception is thrown: System.FormatException;
in System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
in System.Single.Parse(String s)

Operational System:Windows 10 Pro

Version: v1.13.0

**Comment by jean-knapp** [comment]
Soundscape issues have been fixed in newer versions. v1.13 won`t receive updates, I don`t have the source code anymore.
