### ISSUE TITLE
Catastrophic Failure

### ISSUE THREAD

**Issue by BlackMesa2006** [jean-knapp/xblah-modding-tool-public#11]
i cannot export the file, because every time i do it says catastrophic failure

**Comment by UsernameZer0** [comment]
Are you talking about the 7z file? If so, the way I did it is to avoid extracting any other folder in lib other than win32 (if you can open archives)

**Comment by jean-knapp** [comment]
v,2.0.5 and newer solve this. I've removed these linux dependencies.
