### ISSUE TITLE
running with wine dosen't work

### ISSUE THREAD

**Issue by rewixx** [jean-knapp/xblah-modding-tool-public#12]
error returned:
`Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'DevExpress.Utils.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies.
File name: 'DevExpress.Utils.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'DevExpress.Utils.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies.
`

**Comment by jean-knapp** [comment]
Linux is not supported, sorry.
