### ISSUE TITLE
unusual power usage?

### ISSUE THREAD

**Issue by justinsly** [jean-knapp/xblah-modding-tool-public#15]
![image](https://github.com/jean-knapp/xblah-modding-tool-public/assets/134002548/c73bd292-b14c-423a-baa0-89339dd1a34f)
despite being minimized and not doing anything in the background, task manager shows that the tool's power usage is very high and is using an unnecessary amount of cpu power, is this a normal thing for it to do?

**Comment by jean-knapp** [comment]
The only backgrounds it does, when idle, is downloading updates. That could be it. About power usage, that's an OS thing, I have no control over it.
