### ISSUE TITLE
cant sign in not secure

### ISSUE THREAD

**Issue by breakdowngamesYT** [jean-knapp/xblah-modding-tool-public#4]
error 
Couldn’t sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.

**Comment by jean-knapp** [comment]
Hi. I suggest you create a Patreon account without using Google. One patron mentioned me you can configure patreon to log in without google in case you signed up with it. But if you can't find that option, you can create another account and I'll refund it for you in the first one.
